### ISSUE TITLE
Feedback and Small improvements

### ISSUE THREAD

**Issue by rufuspollock** [Mikanebu/task-for-datopian#1]
Strengths:

* Nicely written script
* Both time periods
* Data is **perfect** (including well formatted dates and handling of N/A)
* datapackage.json pretty much there

Minor improvements

* main.py
  * Encapsulate tasks into functions e.g. daily data and monthly data
  * Call functions from __main__.py
* README: script commands should be in backticks e.g. `python main.py` vs python main.py
* Dependency (BeautifulSoup) in a requirements.txt
* Data Package
  * monthly data not in datapackage.json
  * path should be `daily.csv` not `./daily.csv`
  * structure the data package in standard way: scripts in `scripts/`, data in `data/` etc

Big comment: you could just download the excel file rather than do html scraping :wink: (though both work fine)

**Comment by Mikanebu** [comment]
FIXED
